### ISSUE TITLE
Toast don't working.

### ISSUE THREAD

**Issue by fukhaos** [mateuszmackowiak/NativeDialogs#1]
First, amazing update. :+1: 
Second the Toast show "true" when Toast.isSupported
but dont show nothing. (Using iPad 2 with IOS 6.)

and another question.

will have ?:
NativeProgress.showNetworkActivityIndicator(true);

**Comment by mateuszmackowiak** [comment]
I'm working on the toast right now.
But "NetworkActivityIndicator" will be probably moved to SystemProperties.

**Comment by mateuszmackowiak** [comment]
Toast fixed in 784f04e273 commit.

**Comment by mateuszmackowiak** [comment]
NetworkActivityIndicator has been moved to 
https://github.com/mateuszmackowiak/SystemProperties

and the method to use is "setNetworkActivityIndicatorVisibility"
