### ISSUE TITLE
Feature request - Access which button was pressed when closing a dialog alert

### ISSUE THREAD

**Issue by GonzOne** [mateuszmackowiak/NativeDialogs#11]
It would be useful to know which button was triggered.

private function showSaveAlert():void
{
 var saveNativeAler:NativeAlertDialogt = NativeAlertDialog.show(SAVE_MESSAGE, TITLE, "Save", "Cancel", saveHandler);

}

private function saveHandler(event:NativeDialogEvent):void
{
    var selectedButtonLabel:String= event.currentTarget.label;//would suffice
    switch(selectedButtonLabel)
    {
           case "Save":
        saveImage();
        break;
        case "Cancel":
        doSomethingElse();
        break;
    }

}

**Comment by mateuszmackowiak** [comment]
NativeDialogEvent has a index property that returns the index of the pressed button.

**Comment by GonzOne** [comment]
Error #1069: Property index not found on pl.mateuszmackowiak.nativeANE.dialogs.NativeAlertDialog and there is no default value.

did you mean :

event.target.selectedIndex

event.currentTarget.selectedIndex

??

**Comment by mateuszmackowiak** [comment]
You are trying to access index on the dialog. There is a index propertie on the NativeDialogEvent.
Use event.index
Dnia 5 mar 2013 o godz. 02:06 Manuel Gonzalez notifications@github.com napisał(a):

**Comment by GonzOne** [comment]
Sweet, thanks!
