### ISSUE TITLE
Compilation problem

### ISSUE THREAD

**Issue by Neverbirth** [mateuszmackowiak/NativeDialogs#12]
The ANE cannot be compiled, XCode tries to access some iOS/NativeDialogs/NativeDialogs/aneBuildBefore.sh file not present in the repository.

I see at the end it also tries to run aneBuildAfter.sh.

Compiling without running the scripts is successful although I don't know if this may cause problems, so are they really needed? the resulting ANE is around 500kb smaller.

**Comment by mateuszmackowiak** [comment]
The additional code is only for providing a one library for IOS Simulator and for the device.
It's not needed but I have add it in the last commit.
