### ISSUE TITLE
with the new ".showAlert:, how I made a simple alert with YES and NO ?

### ISSUE THREAD

**Issue by fukhaos** [mateuszmackowiak/NativeDialogs#19]
For me is showing YES, NO and OK.

``` javascript
NativeAlertDialog.showAlert( message , title , new <String>["Yes", "No"] , response);
```

**Comment by makc** [comment]
See [here](https://github.com/mateuszmackowiak/NativeDialogs/commit/0091f280682d9f10f707d89f0865485bf65c467b#L5L286) for the source of your problem. It should have been something like _context.call("showAlertWithTitleAndMessage", _title, _message, _closeLabel = _buttons.pop(), _buttons.join(","... seems that that commit left a lot of old code intact

**Comment by fukhaos** [comment]
hum...
So I will wait for a update !

**Comment by makc** [comment]
You don't have to, you could clone as3 part of extension (under different package name, for example) and have use that instead of repo version. This way you could implement / test bugfixes without building whole ANE.

**Comment by mateuszmackowiak** [comment]
commit 7f79e49 should resolve this problem.
