### ISSUE TITLE
Null error in AS

### ISSUE THREAD

**Issue by mattmurton** [mateuszmackowiak/NativeDialogs#21]
Line 313 in NativeAlertDialog.as currently passes the _buttons vector into the call function. However it is possible that _buttons is null at this point and this breaks the extension.

I changed: '_buttons.join(","),' to '_buttons ? _buttons.join(",") : "" ' and it seems to have fixed it nicely..

Thanks for the great ANE.

**Comment by ghost** [comment]
I had the same problem

**Comment by mateuszmackowiak** [comment]
commit 7f79e49 should resolve this problem.
