### ISSUE TITLE
NativeListDialog in IOS7

### ISSUE THREAD

**Issue by eitho** [mateuszmackowiak/NativeDialogs#23]
in ios7 doesn't show data (dataProvider).

``` ActionScript
var m:NativeListDialog = new NativeListDialog();
*m.title = "Title";
m.message = "Message";
m.buttons = Vector.<String>(["Cancel", "OK"]);
m.dataProvider = Vector.<Object>(["1","2","3","4"]);
m.displayMode = NativeListDialog.DISPLAY_MODE_SINGLE;
m.show();
```

Maybe I do something wrong?

**Comment by NewYor** [comment]
Same here (iOS7 Beta2/iPhone5)

**Comment by jurito** [comment]
I third that, doesn't work on iOS7 officially released either. (iPhone 4 and 5) :\

May i ask if you intend to update it? TIA

**Comment by mola2alex** [comment]
Noticed the same thing, also the progress bar had some issues

**Comment by jurito** [comment]
https://github.com/mindbrix/SBTableAlert appear to have fixed the ios7 issues for the NativeListDialog.

**Comment by mola2alex** [comment]
hopefully the ANE gets updated shortly...I will donate to the project :)

**Comment by sattaman** [comment]
mindbrix's update doesn't seem to have worked for me, @jurito did you ever get it to work?

**Comment by mateuszmackowiak** [comment]
I will fix it on the weekend.

**Comment by eitho** [comment]
goods news :)

**Comment by sattaman** [comment]
brilliant :) cheers

**Comment by mateuszmackowiak** [comment]
Didn't find time for this. But promise to sit down during the week.

**Comment by vorlovsky** [comment]
Any chance you'll be able to investigate and fix it till EOW?
I really need these dialogs to work on iOS7 and don't know if I should start to create the same ones in AS3/Flex instead.

**Comment by mateuszmackowiak** [comment]
I have pushed a commit that is fixing the errors in IOS7. But the problem is that Apple has removed tha ability to add subiews to alert dialgos. So I plan to change it. For now the progress and list dialgos use https://github.com/mindbrix/TSAlertView . For the progress dialog use themes.

**Comment by vorlovsky** [comment]
Thanks for your fix!
Unfortunatelly, if there are more than ~5 items in the list to be visible it still looks bad.

**Comment by eitho** [comment]
Mateusz good work and thanks!

sometimes i have problem (screenshot). can you fix it please?
![img_5704](https://f.cloud.github.com/assets/1749272/1324419/29ddc54a-34b1-11e3-91be-1b8c69c7eb45.PNG)

**Comment by vorlovsky** [comment]
Yes, that's what I meant.

**Comment by mateuszmackowiak** [comment]
Problem solved on the last commit.

**Comment by eitho** [comment]
Mateusz thank you very match. Can you help me. How can I disable orientation on NativeListDialog?
