### ISSUE TITLE
NativeTextInputDialog - Android  - Error

### ISSUE THREAD

**Issue by epartipilo** [mateuszmackowiak/NativeDialogs#24]
Error on creating NativeTextInputDialog instance on Android. (iOS works fine)
![captura de pantalla 2013-06-13 a la s 14 58 28](https://f.cloud.github.com/assets/4688744/648373/01c2d304-d429-11e2-8920-30cb38551e51.png)

**Comment by mattmurton** [comment]
Duplicate of https://github.com/mateuszmackowiak/NativeDialogs/issues/20 see my comment for a fixed version
