### ISSUE TITLE
NativeAlertDialog does not allow configuration of the closeLabel

### ISSUE THREAD

**Issue by hartbit** [mateuszmackowiak/NativeDialogs#28]
I found this ANE today and I must say I'm very happy with it. The only problem I have is that there is no (non-deprecated) way to configured the close label of the NativeAlertDialog. Any ideas of fixing this?

**Comment by weinberg** [comment]
Bump. This would be required for us to use it in a localized application.

**Comment by mateuszmackowiak** [comment]
commit 7f79e49 should resolve this problem.
