### ISSUE TITLE
Use with no buttons will Error

### ISSUE THREAD

**Issue by mani95lisa** [mateuszmackowiak/NativeDialogs#29]
Can I just show one button? Why the close button always shown and I have to set buttons?

  _context.call("showAlertWithTitleAndMessage", _title, _message, _closeLabel,   _buttons.join(","), cancelable, _theme);

If no _buttons or _buttons have no item, will got the Error.

Thank you for the ANE, I want to help a little too, but when I run the build.xml, Got the Error:

  [java] platform.xml is not supported for platform iPhone-x86

Have I miss something? I just changed the AIR SDK PATH to mine
AIR_SDK_PATH = /Applications/Adobe Flash Builder 4.7/sdks/4.6.0

**Comment by YuanbaoDaddy** [comment]
I had the same problem

to display a button, must set buttons parameter = Vector. <String> ([","]), and ok button is not centered.
In addition , title and message are grouped show as message.

**Comment by YuanbaoDaddy** [comment]
Error occurred in  NativeAlertDialog.as 313 line.

_context.call("showAlertWithTitleAndMessage", _title, _message, _closeLabel, _buttons.join(","), cancelable, _theme);

**Comment by mateuszmackowiak** [comment]
commit 7f79e49 should resolve this problem.

mani95lisa - there are more than one references to the AIR SDK. And I'm not sure where they all are.
