### ISSUE TITLE
TextInput can't work.

### ISSUE THREAD

**Issue by englekk** [mateuszmackowiak/NativeDialogs#3]
input text => show NativeProgressDialog => hide NativeProgressDialog => next scene (there is a TextInput) => TextInput can't work. (keyboard does not work)
- but, NativeAlertDialog.show() => TextInput can work.

**Comment by fukhaos** [comment]
same error:

``` javascript
progressPopup = new NativeProgressDialog();
progressPopup.iosTheme = NativeProgressDialog.IOS_SVHUD_BLACK_BACKGROUND_THEME
progressPopup.message = "loading";
progressPopup.showSpinner();
```

When touch the textipunt after show, hide and dispose a NativeProgressDialog
the keyboard show but when press the keys, nothing happens.

**Comment by fukhaos** [comment]
the error occurs when using SVProgressHUD. The simple Alert don't cause error !!!

**Comment by mateuszmackowiak** [comment]
Should be now resolved. Check it out and let me know if it works.

**Comment by fukhaos** [comment]
Thanks for that !!!
I will try, by the way I made a donation !!
Thanks !!

**Comment by fukhaos** [comment]
now works fine !!!

**Comment by mateuszmackowiak** [comment]
Great.
