### ISSUE TITLE
NativeDatePickerDialog does not show correct date on startup

### ISSUE THREAD

**Issue by tiefenauer** [mateuszmackowiak/NativeDialogs#4]
When instantiating a new NativeDatePicerDialog and setting the date, the Date is not shown correctly.

I want the DatePicker to show a specific date (default = today) when it opens. To me it looks as if the date is stored correctly internally, but displayed wrong. The start display is February 5 2013 when open() is called. After changing the date with the UI controls, the (previously correctly stored ) date is overwritten.

Here's my code

``` javascript
private var datePickerDialog:NativeDatePickerDialog = new NativeDatePickerDialog();
datePickerDialog.setDate(new Date());
trace(datePickerDialog.date.toLocaleDateString());
datePickerDialog.addEventListener(Event.CHANGE, function(event:Event):void {
    trace(datePickerDialog.date.toLocaleDateString());
});
datePickerDialog.show(true);
```

Here's the console output (first line = first trace(), all other lines = after date has been changed):
<code>
Fri Feb 22 2013
Wed Feb 6 2013
Thu Feb 7 2013
Fri Feb 8 2013
Sat Feb 9 2013
</code>

on IOS the Date is correctly displayed.

**Comment by mateuszmackowiak** [comment]
Fixed in commit 525c83bb0b . I could use a tester. By the way by default it creates a new Date after calling show method.
