### ISSUE TITLE
NativeDialogAlert hide() freezes app on iOS

### ISSUE THREAD

**Issue by orthatg** [mateuszmackowiak/NativeDialogs#8]
When showing a NativeAlert in iOS and then calling hide(), the alert does indeed hide, but it the app becomes unresponsive.  Using code similar to this:

private var na:NativeAlertDialog;

function show() {
na = NativeAlertDialog.show("message", "My Title", "OK", "Cancel", closeHandler);
setTimeout(someOtherFunc, 2000);
}

function someOtherFunc() {
    na.addEventListener(ErrorEvent.ERROR, onError);
    if (na.isShowing())
        na.hide();
}

// this error handler doesn't actually get fired, which makes sense because it _did_ hide the popup
function onError(e:ErrorEvent) {

}

Tested in iOS 4, iOS 6.

This functionality seems to work fine in Android.

**Comment by mateuszmackowiak** [comment]
The 9018784cf8 commit should resolve the problem.
