### ISSUE TITLE
NativeProgressDialog: Dialog does not get focus

### ISSUE THREAD

**Issue by tiefenauer** [mateuszmackowiak/NativeDialogs#9]
I tested the NativeDialogs-extension with your Test-App and there everything works fine.

However I have a problem in my app:
I have an app doing some initialization before/on startup. The problem is that the ProgressDialog does not show up, until the app is finished! I would like to use the ProgressDialog to show the initialization status, but this seems to be not possible.

I placed an EventListener on the ADDED_TO_STAGE-Event, which launches the initialization. For test purposes, I copy/pasted the code from your example (which worked in your Test-App) to show some dummy progress. I did this just to see if the Dialog opens correctly - it does not!

The ProgressDialog opens only after all the initialization has been done. However, the progress then is at '100%', which indicates that the progress has been launched in the background, but never got focus somehow and therefore was never shown

The code is roughly as follows:

`<s:TabbedViewNavigatorApplication 
    xmlns:fx="http://ns.adobe.com/mxml/2009" 
    xmlns:s="library://ns.adobe.com/flex/spark"
    addedToStage="onAddedToStage(event)"
    >`

```
            protected function onAddedToStage(event:Event):void{
                // this should launch the dialog, but it does only show up after all the initialization has been done   
                var p:NativeProgressDialog = new NativeProgressDialog();
                p.addEventListener(NativeDialogEvent.CANCELED,trace);
                p.secondaryProgress = 45;
                p.max = 50;
                p.title = "Title";
                p.message ="Message";

                progressPopup = p;

                myTimer.addEventListener(TimerEvent.TIMER, updateProgress);
                myTimer.start();

                p.showProgressbar();

                // do some initialization here involving other classes
                foo.bar(some:int, initialization:XML, arguments:String);
            }

            private function updateProgress(event:TimerEvent):void
            {
                var p:int = progressPopup.progress;
                p++;
                if(p>=50){
                    p = 0;
                    progressPopup.hide(1);
                    myTimer.removeEventListener(TimerEvent.TIMER,updateProgress);
                    (event.target as Timer).stop();
                }
                else{
                    if(p==25){
                        progressPopup.shake();
                        //progressPopup.setMessage("some message changed in between");
                        //progressPopup.setTitle("some title changed in between");
                    }
                    try{
                        progressPopup.setProgress(p);
                    }catch(e:Error){
                        trace(e);
                    }
                }
            }
```

If I leave the following line away, everything works as expected (the dummy-NativeProcess is shown and animated):
`foo.bar(some:int, initialization:XML, arguments:String);`
I tried to get a workaround by adding an EventListener on the NativeDialogEvent.OPENED-Event and then launching the initialization-method after the NativeDialog has been opened. However, the NativeDialog is still not opened, although the initialization launches. The code is as follows

```
            protected function onAddedToStage(event:Event):void{
                (...)
                 // rest same as above
                myTimer.start();

                // add event listener on NativeDialog-Opening to launch initialization-method after opening
                p.addEventListener(NativeDialogEvent.OPENED, addArguments(foo.bar, [some, additional, arguments]));
                p.showProgressbar();
                // rest same as above
                (...)
            }

            /**
             * Helper function to create a function which applies arguments to be passed to the initialization function
             */
            private function addArguments(method:Function, additionalArguments:Array):Function{
                return function(event:Event):void {method.apply(null, additionalArguments);}
            }

```

**To me it seems as if the NativeProcess does not correctly request focus and is only displayed, after all other elements have been displayed and all other (initialization-)code has been executed...**

**Comment by mateuszmackowiak** [comment]
I have tested the calls for displaying progress dialog while initializing the app. There was no problem.
Maybe the code for Your initializing was to heavy and the dialog didn't manage to show in time.

**Comment by tiefenauer** [comment]
The initialization is actually quite heavy (parse/copy files from app- to app-storage directory). That's why I wanted to show a progress. 
Am I right assuming that native alerts/progresses/... run in the same thread as the rest of the application? This would be a drawback since these are supposed to be async imo...

Sorry if you got this message twice, I lost connection while sending and it didn't appear in my outbox afterwards. 

Daniel Tiefenauer

Am 05.03.2013 um 01:31 schrieb "Mateusz Maćkowiak" notifications@github.com:

**Comment by mateuszmackowiak** [comment]
All interactions with the User Interface have to be on the main thread so there is no other way.
You can show the progress spinner dialog on the "addedToStage" and run Your initialization code after the dialog opens.
